# Generated by Django 5.2.1 on 2025-07-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_myuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='total_presentations',
        ),
    ]
